### ISSUE TITLE
username and password

### ISSUE THREAD

**Issue by adushui** [hypriot/image-builder-rpi#101]
Excuse me,I have trouble using HypriotOS.
I copied the .img to SDcard and then I tried to log in the system by Xshell but failed with wrong username( pi / root ) or password( raspberry / hypriot ).
Could you tell me corret username&password?Or what should I do to log in?Thank you very much!!

**Comment by Govinda-Fichtner** [comment]
It's pirate and hypriot.
Am 28.05.2016 19:41 schrieb "Shui DuJiang" <notifications@github.com>:

**Comment by adushui** [comment]
thanks
