### ISSUE TITLE
Add pirate user to the "video" group

### ISSUE THREAD

**Issue by marcosnils** [hypriot/image-builder-rpi#108]
If camera is enabled, it won't work by default as users need to be added to this group. This will also reduce friction from new adopters trying to use the camera

**Comment by StefanScherer** [comment]
@marcosnils Thanks, that makes sense. Could you append what is needed in config.txt to enable the camera?

**Comment by marcosnils** [comment]
There are the usual parameters used
```
start_x=1
disable_camera_led=1
gpu_mem=128
```

http://elinux.org/RPiconfig#Camera
