### ISSUE TITLE
Add cgroup_enable=cpuset to /boot/cmdline.txt

### ISSUE THREAD

**Issue by luxas** [hypriot/image-builder-rpi#132]
This is a Kubernetes requirement (hard dependency), ref: https://github.com/kubernetes/kubernetes/issues/26093

It would be great to have it enabled by default, then a reboot isn't necessary when installing Kubernetes on ARM :)

**Comment by StefanScherer** [comment]
Indeed, this would be a great out-of-the-box experience :-) Can I persuade you to send a PR with the change in mind? The /boot/cmdline.txt is created in [builder/chroot-script.sh#L139](https://github.com/hypriot/image-builder-rpi/blob/a47caa671b834e6cd0afd755677ca6a224c76496/builder/chroot-script.sh#L139).
We could draft a pre-release to produce a SD card image to try it out with such a PR.

**Comment by yonatan-schultz** [comment]
I think that something like this will do: https://github.com/hypriot/image-builder-rpi/pull/133

**Comment by DieterReuter** [comment]
Fixed by #133

**Comment by luxas** [comment]
Thanks @yonatan-schultz, was just about to send a PR, but now I have one thing less to do :)

@DieterReuter Any possibility an image with that patch could be produced so I can verify it's working OOTB? I'm releasing Kubernetes on ARM v0.8.0 really soon and it would be awesome with an Hypriot image with this cpuset by default :) (hopefully no reboot required)

**Comment by yonatan-schultz** [comment]
@luxas no problem, thanks for all your work on Kubernetes. docker-multinode is making me very happy (once I found this fix)

**Comment by DieterReuter** [comment]
@luxas I just tested it manually here on my Pi and the new integration tests as well. Will discuss with @StefanScherer to build a pre-release soon.

**Comment by luxas** [comment]
Great, send an email with download info to me when you have it uploaded :+1:

**Comment by DieterReuter** [comment]
@luxas I've just released a new HypriotOS 1.0.1 image for the Raspberry Pi, see https://github.com/hypriot/image-builder-rpi/releases/tag/v1.0.1.
