### ISSUE TITLE
Add pre-installed swarm docker image

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/image-builder-rpi#15]
The old HypriotOS SD card image has the Docker Swarm image pre-installed so you don't need an internet connection to get started with Swarm.
Currently it's missing.
We want to re-add it in our new HypriotOS SD card as well.

**Comment by firecyberice** [comment]
Depends on hypriot/device-init to load the image(s) after boot to make them useable by docker

**Comment by Govinda-Fichtner** [comment]
That's solved since https://github.com/hypriot/image-builder-rpi/releases/tag/v0.5.0
