### ISSUE TITLE
How do we set Docker Proxy?

### ISSUE THREAD

**Issue by yoshihingis** [hypriot/image-builder-rpi#163]
I could install hypriot into Raspberry-pi. But I could pull docker image , I am sure that my company's proxy makes this error.

How do we set Docker proxy?  Do we have to set proxy at /etc/default/docker ?

**Comment by StefanScherer** [comment]
@yoshihingis I cannot test it, but the official docs https://docs.docker.com/engine/admin/systemd/#http-proxy should show you the way how to do it.

**Comment by yoshihingis** [comment]
Thank you for your advice.
I tried to the way which you suggestd, this problem was solved.
Thank you again!
