### ISSUE TITLE
New user .profile contains reference to pirate user

### ISSUE THREAD

**Issue by Duvel** [hypriot/image-builder-rpi#164]
The file .profile only sets the path for the pirate user:

```
if [ "$USER" == "pirate" ]; then
```

Not sure if it is a bug or not, but it doesn't feel right.

Just to be sure I now replaced it like this:

```
sudo sed -i -- 's/pirate/duvel/g' /home/duvel/.profile
```

**Comment by firecyberice** [comment]
The correct code snippet is [here](https://github.com/hypriot/os-rootfs/blob/master/builder/files/etc/skel/.profile#L3)
