### ISSUE TITLE
How to free maximum RAM headless mode with no video

### ISSUE THREAD

**Issue by gdeverlant** [hypriot/image-builder-rpi#171]
Is there a way to max out the RAM and disable all options to make the board headless for the Rpi 1

**Comment by bfqrst** [comment]
...you could reduce the amount of memory allocated for the GPU by setting the `gpu_mem=XX` in your `/boot/config.txt`. I tend to set mine to 32. But you could go as low as 16MB as per [this](https://www.raspberrypi.org/forums/viewtopic.php?t=181262&p=1151589) thread.

Hope that helps.

Cheers
Ralph

**Comment by StefanScherer** [comment]
Thanks @bfqrst for answering the question.
