### ISSUE TITLE
Benchmark Performance drop

### ISSUE THREAD

**Issue by aakashkhochare** [hypriot/image-builder-rpi#173]
I am using the Whetstone Benchmark implemented in Java provided [here](http://roylongbottom.org.uk/Raspberry%20Pi%20Benchmarks.htm#anchor14) on a Raspberry Pi 3. The performance with Hypriotos looks way off the mark.  Results with Hypriot are show below

>   Test                  Result       MFLOPS     MOPS  millisecs
  N1 floating point  -1.124750137      2.77             6.9320
  N2 floating point  -1.131330609      4.36            30.8300
  N3 if then else     1.000000000               1.88   54.9500
  N4 fixed point     12.000000000               5.07   62.1100
  N5 sin,cos etc.     0.499110103               0.64  129.6000
  N6 floating point   0.999999821      1.50           358.6800
  N7 assignments      3.000000000               1.24  148.7900
  N8 exp,sqrt etc.    0.751108646               0.24  154.9300
  MWIPS                               10.56           946.8220
  Operating System    Linux, Arch. arm, Version 4.4.43-hypriotos-v7+
  Java Vendor         Oracle Corporation, Version  1.7.0_121
  CPU null

I know that N1 floating point should not be 2.77 MFLOPS, it should be in the 180s which is a massive performance drop. and I have no clue why.  I have tried out Hypriotos versions 1.4.0 and 1.2.1 and I will be trying out version 1.0.0 soon.

**Comment by StefanScherer** [comment]
Sorry, can't help here. I'm closing this. If you have more information don't hesitate to reopen.
