### ISSUE TITLE
Missing img file for 1.6.0 release

### ISSUE THREAD

**Issue by maxromanovsky** [hypriot/image-builder-rpi#186]
`.img` file for 1.6.0 release is missing on the release page: https://github.com/hypriot/image-builder-rpi/releases/tag/1.6.0

**Comment by StefanScherer** [comment]
Thanks for the heads-up. My fault, Travis didn't trigger the release because I forgot to prepend "v" to the version number.
A new release "v1.6.0" just started a build on Travis https://travis-ci.org/hypriot/image-builder-rpi/builds/280751889
Take about 20-30 minutes...
