### ISSUE TITLE
Why is only older releases on the Hypriot blog?

### ISSUE THREAD

**Issue by krokofant** [hypriot/image-builder-rpi#199]
Not sure if I should use the old builds to start play around or if I can use the new shiny releases. I didn't see any notes about releases being stable/unstable either so I don't understand which I should pick.

Thanks!

**Comment by jswetzen** [comment]
I had some problems with 1.5.0 and came here to open an issue, when I found lots of new releases! Of course, it's a bit of work to update that blog every time, so I made a pull request to get it up-to-date for now at least.
