### ISSUE TITLE
Where is device-init on v1.7.1?

### ISSUE THREAD

**Issue by potatop** [hypriot/image-builder-rpi#202]
There is no device-init at /usr/local/bin, and device-init.yaml file at /boot has no effect. Hostname is still black-pearl and wifi did not start. 
Did cloud-init replace device-init?

**Comment by StefanScherer** [comment]
Exactly. Cloud-init is more flexible and better known and there are more docs out there. 
Have a look at the latest blog post and the /boot/user-data file.

**Comment by potatop** [comment]
Was this stated some where? It's not clear from the release notes.

**Comment by StefanScherer** [comment]
Oh you‘re right, we should mention it in https://github.com/hypriot/image-builder-rpi/releases/tag/v1.7.1 intoduced with 1.7.0 and some housekeeping in the download page. 
I‘ll reopen this issue for these tasks.

**Comment by StefanScherer** [comment]
I've added 

```
## Breaking change
- No more device-init, please convert your `/boot/device-init.yaml` to `/boot/user-data`
```

to the 1.7.0 and 1.7.1 releases.

**Comment by potatop** [comment]
Thanks.

**Comment by maxnowack** [comment]
There also should be a mention about that change in the readme of this repository: https://github.com/hypriot/device-init
