### ISSUE TITLE
Docker stuck on 17.05.0-ce (2017-05-04)

### ISSUE THREAD

**Issue by NargiT** [hypriot/image-builder-rpi#204]
Hello,

My version of docker is stuck on 17.05.0-ce version but the latest is 17.11 and even the stable version is 17.09 (source : https://docs.docker.com/release-notes/docker-ce/)

I don't understand why 
`sudo apt-get update && sudo apt-get upgrade` do not upgrade :( I also tried dist-upgrade but nothing...

any idea ?

**Comment by StefanScherer** [comment]
Docker has changed the repo and package name. I don‘t know a safe upgrade path. 

To install current versions you can use

```
curl https://get.docker.com | sh
```

But I don‘t know if you loose your images.

**Comment by NargiT** [comment]
Yes you were right

I updated /etc/apt/sources.list.d/docker.list by 
deb [arch=armhf] https://download.docker.com/linux/raspbian jessie stable
and I have now the version I wanted
thx
