### ISSUE TITLE
Does the image use SELinux or AppArmor? 

### ISSUE THREAD

**Issue by scud3r1a** [hypriot/image-builder-rpi#211]
Does the image use SELinux or AppArmor? If not, should it?
This image is based on Raspbian, isn't it?

Thanks!

**Comment by StefanScherer** [comment]
I'm not aware that we have added SELinux or AppArmor. What is your use-case?
Yes, the SD card image is based on Raspbian, the rootfs is built at https://github.com/hypriot/os-rootfs
Some tools are missing and due to the other kernel you may find issues with additional hardware.

**Comment by scud3r1a** [comment]
Thank you very much for your quick answer. I cannot name a specific use-case. But I read about the discussion to connect e.g. AppArmor and Docker multiple times. Would it make the system safer in your opinion?

**Comment by StefanScherer** [comment]
Yes, the docker-ce packages installs libapparmor as dependency https://travis-ci.org/hypriot/image-builder-rpi/jobs/322848909#L2123

But it is up to the user to use the Docker options to run containers more securely.

**Comment by scud3r1a** [comment]
So you have not set that up yet in general? For other applications?
Can you guess if Raspbian uses AppArmor by default?

**Comment by StefanScherer** [comment]
No I don't know. Please use https://gitter.im/hypriot/talk for more questions / discussions. :-)
