### ISSUE TITLE
Internet connectivity 

### ISSUE THREAD

**Issue by khwerhahn** [hypriot/image-builder-rpi#218]
Hi,

something very strange. Some of the images I created on OSX:
```
flash --hostname node02 ~/Downloads/hypriotos-rpi-v1.7.1.img.zip
```
are not able to connect to the internet via ethernet, even though some some of them with the exact same procedure are able to connect.

Logging into the PIs and trying to sudo apt-get update don't work due to missing internet connectivity. 

Any ideas of what this could be?

**Comment by StefanScherer** [comment]
Strange. Check `ifconfig`, `/var/log/messages` or `sudo dmesg` if there are errors.
