### ISSUE TITLE
Hypriot to be based on Alpine ?

### ISSUE THREAD

**Issue by nsteinmetz** [hypriot/image-builder-rpi#253]
Hello there,

With Alpine 3.8 having support of RPI3, I was wondering if you are to release a Hypriot OS version, based on Alpine instead of raspbian ?

https://alpinelinux.org/posts/Alpine-3.8.0-released.html

```
New features and noteworthy new packages

    Support netboot on all architectures
    Add arm64 (aarch64) Raspberry Pi image
    Add support for Raspberry Pi 3 Model B+
    Support ISO image on s390x (KVM installation)
    End of support for hardened kernel (unofficial Grsecurity)
    Support for Crystal language

Significant updates

    Linux 4.14
    Go 1.10
    Node.js 8.11 (LTS)
    Rust 1.26
    Ruby 2.5
    PHP 7.2
    ghc 8.4
    OCaml 4.06
    R 3.5
    JRuby 9.2
```
I know it does not match for other RPI versions but at least it would be lightweight !

**Comment by DieterReuter** [comment]
That's really a great idea! But not sure if I will have the time for...

**Comment by nsteinmetz** [comment]
Perhaps I can work on it after summler break with some mentoring or minimal set of instructions.

**Comment by 74cmonty** [comment]
Just a comment: the new Alpine release 3.8 is "designed for RPI 1,2 and 3".

**Comment by ulm0** [comment]
Wow, this might be a really nice flavor!

**Comment by toddbu** [comment]
I'd urge caution jumping in on this. About a year ago and after many days of debugging, I was not able to get node.js to run in an Alpine container running on an Alpine host. It wouldn't even start. I use Alpine exclusively for all my deployments and never had this issue with any other Docker host (Ubuntu, CoreOS, or Raspbian)

**Comment by StefanScherer** [comment]
As we do not have time for such adventures  I'll close the ticket.

**Comment by nsteinmetz** [comment]
Indeed - lack of time also on my side for this challenge - sorry and may be next time ;-)
