### ISSUE TITLE
Updating the linux kernel

### ISSUE THREAD

**Issue by arnulfojr** [hypriot/image-builder-rpi#256]
Is there a way to be able to update the linux kernel?
related issue https://github.com/raspberrypi/linux/issues/2580

How safe is it to use `rpi-update` command?

**Comment by StefanScherer** [comment]
Check the latest 1.10.0 pre-release, we're moving to upstream Raspbian Linux kernel.

**Comment by arrelid** [comment]
Upstream seems to be at [4.19 as of recently](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=224931) - any chance 1.10 will be updated to it?

**Comment by StefanScherer** [comment]
@arrelid Raspbian is still on 4.14. Updating to latest bits with #280 for a 1.10 release

**Comment by StefanScherer** [comment]
Hypriot 1.11 has kernel 4.19
