### ISSUE TITLE
rspec no longer passing

### ISSUE THREAD

**Issue by Noext** [hypriot/image-builder-rpi#267]
hello, i'm using cercleCI to build custom image of Hypriot

since last week my builds no longer working 

here is log of rspec : https://pastebin.com/yVPCa0u6

my versions.config : https://pastebin.com/aV41w5Ey

my last build was 7 day ago and was ok, and now without any update to my code, the image is no longer working 

do you know if any of the third party repo used by the build process has been updated and can cause this ?

edit : got the same result on a local ubuntu vm

**Comment by StefanScherer** [comment]
A current CircleCI build worked fine.
