### ISSUE TITLE
Disabling onboard wifi on RPi 3B/B+

### ISSUE THREAD

**Issue by flochtililoch** [hypriot/image-builder-rpi#277]
Adding [`dtoverlay=pi3-disable-wifi` in /boot/config.txt](https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README#L1408-L1411) does not appear to work in my tests. I'm running Hypriot 1.9 on two different raspberry pis (3B+ / 3B) and configured them as such, but their wlan0 interface seem to remain active. Not too sure where to investigate, do you have any idea what might be going wrong?

**Comment by numberformat** [comment]
Adding dtoverlay=disable-wifi in /boot/config.txt worked for me in 1.11.4
