### ISSUE TITLE
Can't build on gitlab CI

### ISSUE THREAD

**Issue by marclennox** [hypriot/image-builder-rpi#289]
I'm trying to build a fork of this project using Gitlab CI, but it seems the guestfish step is failing because the the `/boot` mount from the Docker host is empty.  I see that in order for this to work in Circle CI, a `machine` executor must be used.

Do you have any suggestions how the build could be modified to work on Gitlab CI?

**Comment by StefanScherer** [comment]
You can fork our repo and hook it up to CircleCi, that's the easiest way I can recommend.
I can't help for Gitlab CI.
