### ISSUE TITLE
Switching SD card between RPi's: eth1: renamed from eth0

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/image-builder-rpi#31]
When I boot a RPi with the v0.4.0 SD card image, shutdown and plug the SD card into another RPi, then the network does not work.

In /var/log/messages I see a message like

```
eth1: renamed from eth0
```

Probably due to the different MAC addresses of the RPi's

**Comment by DieterReuter** [comment]
Just tested it, booting RPi3 first and then used the same SD card in a RPi2. Here are the messages from `dmesg` command:
```
$ dmesg | grep eth
[    3.139465] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:d5:98:5b
[    5.653463] smsc95xx 1-1.1:1.0 eth1: renamed from eth0
[    5.745601] systemd-udevd[112]: renamed network interface eth0 to eth1
```

**Comment by DieterReuter** [comment]
This could be easily fixed in `/etc/systemd/network/eth0.network`, just use 
```
[Match]
Name=eth*
```
instead of `Name=eth1`.

**Comment by DieterReuter** [comment]
Can be fixed with https://github.com/hypriot/os-rootfs/pull/25.
