### ISSUE TITLE
Edit Cloud-Init after first boot

### ISSUE THREAD

**Issue by bd8392** [hypriot/image-builder-rpi#325]
Hi,

I don't know if this is even possible but I tried to edit the user-data under /boot after the very first boot of hypriot, but it didn't take effect...is there another way? Because I want to test multiple cloud-init possibilities without always set up a new machine...

**Comment by bd8392** [comment]
Found it out! With the command: "sudo cloud-init clean" you can tell cloud init to run at next reboot =)

**Comment by StefanScherer** [comment]
Thanks @bd8392 for sharing the solution!

**Comment by bd8392** [comment]
@StefanScherer no problem :-) but be careful when using it. When I got it right, it doesn't revert the configs that the previous Cloud-init made, but applies the new ones over it...so you maybe get mixed up with settings when rerunning cloud-init...
