### ISSUE TITLE
wpa_supplicant?!

### ISSUE THREAD

**Issue by jeffrson** [hypriot/image-builder-rpi#326]
Hi,

I cannot input WIFI credentials, because (in raspi-config) choosing WIFI country as well as trying to connect both output "cannot communicate with wpa_supplicant".

This is a Raspberry Pi 3, Hypriot 1.11.3.

cloud-init during boot appears to find both eth0 and wlan0.

What can I do?

**Comment by StefanScherer** [comment]
Please have a look at https://github.com/hypriot/blog/pull/102
I've updated the FAQ to add the country setting. Without this line the WiFi won't start with recent Hypriot SD cards.
