### ISSUE TITLE
raspi-config cannot select keyboard

### ISSUE THREAD

**Issue by jeffrson** [hypriot/image-builder-rpi#327]
Hi

as soon as I want to choose localization/keyboard there's an error message that disappears too fast to be read, and raspi-config returns to the main menu.

Any idea?

**Comment by dneckel** [comment]
Seems like the keyboard-configuration is not installed, I ran into the same problem.
You can fix this for now by running `sudo apt install keyboard-configuration`
The `raspi-config` option will work afterwards.

**Comment by StefanScherer** [comment]
Thanks for sharing the solution. Closing this now.
