### ISSUE TITLE
Is heredoc correct?

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/image-builder-rpi#4]
I wonder if this heredoc works in line 61 https://github.com/hypriot/image-builder-rpi/blob/master/build.sh#L61

```
chroot ${BUILD_PATH} /bin/bash <<"EOCHROOT"
```

as it should expand variables for FSTAB in line 84 https://github.com/hypriot/image-builder-rpi/blob/master/build.sh#L84

```
  echo ${FSTAB} > /etc/fstab
```

I thought expansion needs a heredoc without the quotes.
I'll test inside a vagrant box.

**Comment by DieterReuter** [comment]
The heredoc has to be this way with chroot! So, that's absolute correct in  https://github.com/hypriot/image-builder-rpi/blob/master/build.sh#L61. Without the quotes in `<<"EOCHROOT"` you'll get an error.

**Comment by StefanScherer** [comment]
So we can pin all the kernel packages by using the KERNEL_* variables, that part is missing ;-)

**Comment by StefanScherer** [comment]
I have added a test to proof that /etc/fstab is correct in #3

**Comment by StefanScherer** [comment]
@DieterReuter Are you sure? The test in build https://travis-ci.org/hypriot/image-builder-rpi/builds/101444491 says "empty" /etc/fstab.

**Comment by StefanScherer** [comment]
resolved in the meantime
