### ISSUE TITLE
crda package is missing

### ISSUE THREAD

**Issue by leanderjanssen** [hypriot/image-builder-rpi#52]
The crda package is not installed by default and this causes some confusing kernel messages:

Jul  3 20:46:46 localhost kernel: [   31.169414] cfg80211: Calling CRDA to update world regulatory domain
...
Jul  3 20:46:52 localhost kernel: [   37.489422] cfg80211: Calling CRDA to update world regulatory domain
Jul  3 20:46:56 localhost kernel: [   40.649426] cfg80211: Exceeded CRDA call max attempts. Not calling CRDA

This is easily solved by including the crda package in the chroot-script.sh

```
# install packages for managing wireless interfaces
apt-get install -y \
  wpasupplicant \
  wireless-tools \
  ethtool \
  crda
```

**Comment by Govinda-Fichtner** [comment]
@leanderjanssen Thanks for filing this issue. Gonna add that asap.
