### ISSUE TITLE
Make /etc/os-release compatible w/ docker-machine

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/image-builder-rpi#79]
Introduce the os-rootfs v0.8.6 to make `/etc/os-release` compatible with docker-machine.

The change in the rootfs is that the /etc/os-release file contains `ID=debian` instead of `ID=raspbian`.

That simplifies the use of the original docker-machine binary to connect a RPi with the generic driver.

**Comment by StefanScherer** [comment]
See also hypriot/os-rootfs#36

**Comment by jmMeessen** [comment]
Thank you !
