### ISSUE TITLE
docker-machine will hang docker daemon

### ISSUE THREAD

**Issue by richtong** [hypriot/image-builder-rpi#80]
Ok the symptom is that with build 0.5.14, this image converted to using `/etc/docker/daemon.json` for its configuration and `/etc/systemd/system/docker.service` has a generic `/usr/bin/docker` start line. 

This is because the main docker-machine does not respect the daemon.json logic and will add it's own command line options and by design the daemon will not start. See https://github.com/docker/machine/issues/3062. 

Reproduce by:

If you run `docker-machine -d generic` against this image with docker-machine 0.6 that is in docker for mac, it does not know about `daemon.json` and instead adds its configuration in the command line of `/etc/systemd/system/docker.service`.

This is the specific behavior of the docker daemon (see https://docs.docker.com/engine/reference/commandline/daemon/) so right now the -H options in the command line conflict with the fd:// option and overlay is specified in both.

When the command line and the daemon.json exist, docker will refuse to start. As an aside, if you are using Docker for Mac beta, it does not update any of the command line utilities, so you need to install Docker Toolbox for Mac to get the latest or run the latest installation scripts

The fix: document that if you use `docker-machine` you must remove daemon.json before running docker-machine create

**Comment by StefanScherer** [comment]
Just for the records: With 0.5.4 we introduced Docker 1.11.1,
a VirtualBox machine 1.11.1 also does not contain any daemon.json file.

**Comment by richtong** [comment]
Oops fixed the version numbers should say 0.5.14. I know 0.5.2 works for sure.

**Comment by richtong** [comment]
Also wants sure if I should post to this or to docker-hypriot, but `apt-get install docker-hypriot` is also broken. Still on 1.10 and it fails to install properly with 0.5.14. I haven't had time to investigate, but perhaps you should bump release that.

**Comment by StefanScherer** [comment]
@richtong To install docker-hypriot I guess you have to remove the package docker-engine manually. There are no dependencies between these two packages.

**Comment by StefanScherer** [comment]
The /etc/docker/daemon.json was introduced in v0.5.5 with commit https://github.com/hypriot/image-builder-rpi/commit/f09778ce7deda95fceb8b712d04b597f73191e0a

We have to remove it for now to make the default SD image docker-machine compatible. Overlay and local unix socket can be achieved w/o this file as well.

**Comment by StefanScherer** [comment]
Instead of removing /et/docker/daemon.json we can just make it empty with only 

```
{
}
```

This solves the docker-machine problem.

**Comment by richtong** [comment]
Thanks I see sounds like the blog needs to deprecate docker-hypriot and use docker-engine instead then. That is way more standard! Nice work testing 0.5.15 now.
