### ISSUE TITLE
Regenerate SSH keys

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/image-builder-rpi#9]
A first boot should run 

```
rm /etc/ssh/ssh_host_*
dpkg-reconfigure openssh-server
```

See https://github.com/hypriot/os-rootfs/issues/3

**Comment by djmaze** [comment]
I think this needs to be handled inside the rootfs image. See the issue for a reasoning.

**Comment by Govinda-Fichtner** [comment]
This is fixed by https://github.com/hypriot/os-rootfs/pull/7
