### ISSUE TITLE
Change to Jessie for the Schatzkiste Repo

### ISSUE THREAD

**Issue by Govinda-Fichtner** [hypriot/image-builder-rpi#94]
https://github.com/hypriot/image-builder-rpi/blob/master/builder/chroot-script.sh#L18 needs to be changed to 'jessie'.

* [x] check docker-machine package in packagecloud
  * fixed with https://github.com/hypriot/arm-machine/commit/ba934471fbef66ee6d4c6a683463eb58380c954e
* [x] check docker-compose package in packagecloud
* [x] check hypriot-cluster-lab package in packagecloud
* [ ] deploy multiple device-init packages to packagecloud

**Comment by StefanScherer** [comment]
Who wants to fix the other build steps instead of manually adding the missing packages to Schatzkiste?

**Comment by Govinda-Fichtner** [comment]
@MathiasRenner @firecyberice Seems like good job for one of you. Basically the existing uploads need to extended to not only upload it to the existing 'wheezy' flavour but also to 

- debian/jessie
- rasbian/wheezy
- rasbian/jessie
